[default]
input = "./data/frames/default"
output = "./data/out_default/default_stack.jpeg"
sigma = 3.0
sigma_iters = 2
chunk_size = 5
align = true
use_memmap = true
normalize = true

[deep_sky]
input = "./data/frames/deep_frames"
output = "./data/out_deep/deep_stack.jpeg"
sigma = 3.0
sigma_iters = 3
chunk_size = 5
align = true
use_memmap = true
normalize = true

[quick]
input = "./data/frames/quick_frames"
output = "./data/out_quick/quick.jpeg"
# Faster/less RAM: fewer sigma iters + smaller chunking.
sigma = 3.0
sigma_iters = 1
chunk_size = 5
align = true
use_memmap = true
normalize = true
